# Generated by Django 4.2.4 on 2023-09-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_key_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key_user',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Ключ'),
        ),
    ]
