# Generated by Django 4.2.4 on 2023-08-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Содержание')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_Blog/', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ('title',),
            },
        ),
    ]
