# Generated by Django 4.2.4 on 2023-08-10 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование категории')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='описание категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование продукта')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='описание продукта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_Product/', verbose_name='изображение')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='цена')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('last_modified_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата последнего изменения')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('name',),
            },
        ),
    ]
